import Head from 'next/head'
import 'animate.css';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Link from 'next/link'
import Discover from '../components/Discover'
import OurServices from '../components/OurServices'
import Facilities from '../components/Facilities'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eatiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favi.png" />
      </Head>

      <main className={styles.main}>
        {/* FIRST SECTION */}
        <div className={styles.firstSection}>
          {/* LEFT SECTION */}
          <div className={styles.leftSection}>
            <div><Navbar /></div>
            <div><Discover/></div>
          </div>

          {/* RIGHT SECTION */}
          <div className={styles.rightSection}>
            <div>
               <div className={styles.user}>
                  <Image src="/Mask.png" alt="User Logo" width={50} height={50} />
                  <Link href="#">User</Link>
               </div>
            </div>            
          </div>          
        </div>

        {/* SERVICES */}
          <div><OurServices/></div>
          <Facilities/>     
      </main>

      {/* FOOTER */}
      <footer className={styles.footer}>
        <Footer/>
      </footer>
    </div>
  )
}
